import type { ReviewTarget, Topic } from '../../src/shared/contracts';
import { test, expect, createProblem, currentAttempt, finish, openLibrary, startTargeted } from './helpers';

test('targeted solve autosaves CodeMirror, reloads draft, and closes unknown time with no review', async ({ page, api }) => {
  await openLibrary(page);
  const problem = await createProblem(api, 'reverse-linked-list', 'Journey Draft Recovery');
  const before = await api.read<Topic[]>('/topics');
  await startTargeted(page, problem);
  const code = 'def reverseList(head):\n    # Acceptance fixture, not executed locally\n    return head';
  await page.locator('.cm-content').fill(code);
  await page.getByLabel('Attempt notes', { exact: true }).fill('Recovered notes with <b>literal markup</b>.');
  await expect(page.getByText('Draft saved', { exact: true })).toBeVisible();
  let attempt = await currentAttempt(page, api);
  expect(attempt.code).toBe(code);
  // Opening catalogue details records disclosure before targeted practice.
  expect(attempt.evidence).toBe('retention');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Resume timer', exact: true })).toBeEnabled();
  await page.reload();
  await expect(page.locator('.cm-content')).toContainText('def reverseList(head):');
  await expect(page.getByLabel('Attempt notes', { exact: true })).toHaveValue('Recovered notes with <b>literal markup</b>.');
  attempt = await currentAttempt(page, api);
  expect(attempt.status).toBe('paused');
  expect(attempt.code).toBe(code);
  await page.getByRole('button', { name: 'Resume timer', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeEnabled();
  await finish(page, { seconds: null, review: 'none' });
  attempt = await currentAttempt(page, api);
  expect(attempt).toMatchObject({ status: 'completed', activeSeconds: null, nextReviewDate: null, reviewedAt: null, code });
  expect(await api.read<Topic[]>('/topics')).toEqual(before);
  const reviews = await api.read<ReviewTarget[]>('/reviews');
  expect(reviews.find(review => review.problemId === problem.id)).toMatchObject({ action: 'none', effectiveDate: null });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Awaiting tutor review', exact: true })).toBeVisible();
  await expect(page.getByText('Next review: Not scheduled', { exact: true })).toBeVisible();
  await expect(page.locator('.cm-content')).toContainText('def reverseList(head):');
  await expect(page.locator('.cm-content')).toHaveAttribute('contenteditable', 'false');
  await page.getByRole('link', { name: 'Done for now', exact: true }).click();
  await expect(page.locator('.recent-practice').getByRole('row').filter({ hasText: problem.title })).toContainText('Unknown');
  await page.goto(`/library?search=${encodeURIComponent(problem.title)}&status=completed&timeBucket=unknown`);
  await expect(page.locator('.library-results h2')).toHaveText('1 question');
  await expect(page.locator('.problem-table tbody tr')).toContainText('Unknown');
});
