import type { ReviewTarget, Topic } from '../../src/shared/contracts';
import { test, expect, createProblem, currentAttempt, finish, openLibrary, startTargeted } from './helpers';

test('result report autosaves notes and code, reloads, and saves LeetCode time with no review', async ({ page, api }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Make room for practice' })).toBeVisible();
  await page.getByRole('button', { name: 'Create my workspace' }).click();
  await expect(page.getByRole('heading', { name: /^Good (morning|afternoon|evening)$/ })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: /^Good (morning|afternoon|evening)$/ })).toBeVisible();
  await openLibrary(page);
  const problem = await createProblem(api, 'reverse-linked-list-qa', 'Journey Draft Recovery');
  const before = await api.read<Topic[]>('/topics');
  await startTargeted(page, problem);
  await page.getByRole('button', { name: 'Save attempt', exact: true }).click();
  expect((await currentAttempt(page, api)).status).toBe('active');
  await page.getByLabel('LeetCode time', { exact: true }).fill('9:53');
  await page.getByRole('button', { name: 'Save attempt', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Paste your solution code');
  expect((await currentAttempt(page, api)).status).toBe('active');
  const code = 'def reverseList(head):\n    # Acceptance fixture, not executed locally\n    return head';
  await page.locator('.cm-content').fill(code);
  await page.getByLabel('Attempt notes', { exact: true }).fill('Recovered notes with <b>literal markup</b>.');
  await expect(page.getByText('Notes and code saved', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Copy code', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Save attempt', exact: true })).toBeVisible();
  let attempt = await currentAttempt(page, api);
  expect(attempt.status).toBe('active');
  expect(attempt.code).toBe(code);
  // Opening catalogue details records disclosure before targeted practice.
  expect(attempt.evidence).toBe('retention');
  await page.reload();
  await expect(page.locator('.cm-content')).toContainText('def reverseList(head):');
  await expect(page.getByLabel('Attempt notes', { exact: true })).toHaveValue('Recovered notes with <b>literal markup</b>.');
  attempt = await currentAttempt(page, api);
  expect(attempt.activeSeconds).toBe(0);
  expect(attempt.code).toBe(code);
  await finish(page, { seconds: 593, review: 'none' });
  attempt = await currentAttempt(page, api);
  expect(attempt).toMatchObject({ status: 'completed', activeSeconds: 593, nextReviewDate: null, reviewedAt: null, code });
  expect(await api.read<Topic[]>('/topics')).toEqual(before);
  const reviews = await api.read<ReviewTarget[]>('/reviews');
  expect(reviews.find(review => review.problemId === problem.id)).toMatchObject({ action: 'none', effectiveDate: null });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Attempt saved', exact: true })).toBeVisible();
  await expect(page.getByText('Next review: Not scheduled', { exact: true })).toBeVisible();
  await expect(page.locator('.cm-content')).toContainText('def reverseList(head):');
  await expect(page.locator('.cm-content')).toHaveAttribute('contenteditable', 'false');
  await page.getByLabel('One-sentence takeaway', { exact: true }).fill('Check the empty input before walking the list.');
  await page.getByRole('checkbox', { name: 'Missed edge case', exact: true }).check();
  await page.getByRole('button', { name: 'Save reflection', exact: true }).click();
  await expect(page.getByText('Reflection saved.', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('One-sentence takeaway', { exact: true })).toHaveValue('Check the empty input before walking the list.');
  await expect(page.getByRole('checkbox', { name: 'Missed edge case', exact: true })).toBeChecked();
  await page.getByRole('link', { name: 'Done for now', exact: true }).click();
  await expect(page.locator('.recent-practice').getByRole('listitem').filter({ hasText: problem.title })).toContainText('9:53');
  await page.goto(`/library?search=${encodeURIComponent(problem.title)}&status=completed&timeBucket=0-10`);
  await expect(page.locator('.library-results h2')).toHaveText('1 question');
  await expect(page.locator('.problem-table tbody tr')).toContainText('9:53');
});
