import { TopicAnalysis } from '../topic-analysis.js';
import { randomUUID } from 'node:crypto';
import type { Topic } from '../../shared/contracts.js';
import type { Store } from '../store.js';
import { Insights, fingerprint } from './service.js';
import { ANALYSIS_VERSION, type Observation } from '../../shared/insights.js';
/** Synthetic fixture only. Never invoked for a personal workspace. */
export function seedInsightDemo(store: Store) {
  if (!store.all<Topic>('topics').length)
    for (const [index, name] of [
      'Arrays',
      'Binary Search',
      'Dynamic Programming',
      'Trees',
    ].entries())
      store.put('topics', {
        id: `demo-topic-${index}`,
        name,
        score: index === 3 ? null : index + 1,
        version: 1,
        notes: 'Synthetic demo score.',
        lastReviewed: null,
        provisional: true,
        lastMovement: null,
      } satisfies Topic);
  const topicAnalysis = new TopicAnalysis(store, () => new Date());
  topicAnalysis.put({
    ...topicAnalysis.record(),
    enabled: true,
    status: 'done',
    fingerprint: topicAnalysis.fingerprint(),
    report: {
      fingerprint: topicAnalysis.fingerprint(),
      createdAt: new Date().toISOString(),
      model: 'synthetic-demo',
      topicIds: topicAnalysis
        .topics()
        .slice(0, 3)
        .map((t) => t.id),
      topicPriorities: topicAnalysis.topics().map((t) => ({
        topicId: t.id,
        importance: 'high',
        reason: 'Illustrative interview priority for this demo.',
        action: 'Try a fresh problem without hints and explain your approach aloud.',
      })),
    },
  });
  const service = new Insights(
    store,
    () => new Date(),
    async () => [],
  );
  const attempts = service
    .attempts()
    .filter((a) => a.notes.includes('I forgot to check an empty input.'))
    .slice(0, 2);
  if (attempts.length < 2) return;
  service.put({ id: 'state', kind: 'state', enabled: false });
  const observations = attempts.map((a) =>
    service.put<Observation>({
      id: randomUUID(),
      kind: 'observation',
      attemptId: a.id,
      problemId: a.problemId,
      fingerprint: fingerprint(a),
      summary: 'The reflection reports overlooking an empty input.',
      polarity: 'difficulty',
      evidenceType: 'learner_reported',
      sourceField: 'notes',
      excerpt: 'I forgot to check an empty input.',
      createdAt: new Date().toISOString(),
      analysisVersion: ANALYSIS_VERSION,
      model: 'synthetic-demo',
    }),
  );
  service.put({
    id: randomUUID(),
    kind: 'report',
    createdAt: new Date().toISOString(),
    fingerprint: service.corpusFingerprint(),
    analyzed: 2,
    total: service.attempts().length,
    evidenceIds: observations.map((o) => o.id),
    model: 'synthetic-demo',
    analysisVersion: ANALYSIS_VERSION,
    durationMs: 0,
    findings: [
      {
        title: 'Check boundary cases',
        kind: 'recurring',
        explanation:
          'Two sample reflections report overlooking empty input. This suggests a testing habit worth practising across problems.',
        action:
          'Trace an empty input, one element, and repeated values before submitting, when the problem permits those inputs.',
        evidenceIds: observations.map((o) => o.id),
        caveat:
          'These are self-reported difficulties in synthetic records, not verified code failures.',
        suggestions: [
          {
            problemId: attempts[0].problemId,
            reason:
              'Revisit this recorded difficulty and explain which boundary cases its actual constraints permit.',
          },
        ],
      },
    ],
    limitation:
      'Illustrative demo report, not generated by a connected tutor. Two synthetic reflections shown; no measured learning improvement.',
  });
}
