import { Children, cloneElement, isValidElement, useId, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import type { Attempt, ScoreDecision } from '../shared/contracts';
export function PageTitle({title, description, children}:{title:string;description?:string;children?:ReactNode}) { return <header className="page-title"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{children}</header>; }
export function Empty({children}:{children:ReactNode}) { return <div className="empty">{children}</div>; }
export function ErrorNotice({error,retry}:{error:unknown;retry?:()=>void}) { if (!error) return null; return <div role="alert" className="error"><span>{error instanceof Error ? error.message : 'Something went wrong.'}</span>{retry && <button onClick={retry}>Retry</button>}</div>; }
export function Loading() { return <div className="loading" role="status">Loading your study records…</div>; }
export function Field({label, children}:{label:string;children:ReactNode}) { const id=useId(); return <label className="field"><span id={id}>{label}</span>{Children.map(children,child=>isValidElement<Record<string,unknown>>(child)&&['input','select','textarea'].includes(String(child.type))?cloneElement(child,{'aria-labelledby':id}):child)}</label>; }
export function duration(seconds:number|null) { if (seconds === null) return 'Unknown'; return `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`; }
export function dateLabel(value:string|null) { if (!value) return 'Not recorded'; if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return new Date(value+'T12:00:00').toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'}); return new Date(value).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'}); }
export function MovementList({items}:{items:ScoreDecision[]}) { return items.length ? <ul className="movement-list">{items.map(item=><li key={item.id}><div className="row between"><Link to={`/topics/${item.topicId}`}>{item.topicName}</Link><span className={item.newScore>item.oldScore?'positive':item.newScore<item.oldScore?'negative':'muted'}>{item.oldScore===item.newScore?'No change':`${item.oldScore} → ${item.newScore}`}</span></div><p>{item.rationale}</p><div className="row small muted"><span>{dateLabel(item.date)}</span><span>{item.evidence.replaceAll('_',' ')}</span>{item.attemptId && <Link to={`/attempts/${item.attemptId}`}>View evidence</Link>}</div></li>)}</ul> : <Empty>No score decisions yet. Scores change only when supported by a review.</Empty>; }
export function AttemptList({items}:{items:Attempt[]}) { return items.length ? <div className="table-scroll"><table><thead><tr><th>Problem</th><th>Outcome</th><th>Active time</th><th>Evidence / help</th><th>Review</th></tr></thead><tbody>{items.map(a=><tr key={a.id}><td><Link to={`/attempts/${a.id}`}>{a.problem.title}</Link><small>{dateLabel(a.finishedAt??a.startedAt)}</small></td><td>{a.outcome?.replaceAll('_',' ')??a.status}</td><td>{duration(a.activeSeconds)}</td><td>{a.evidence?.replaceAll('_',' ')}<small>{a.help==='none'?'No help':`${a.help} help`}</small></td><td>{a.reviewedAt?'Reviewed':a.status==='completed'?'Awaiting tutor review':'In progress'}</td></tr>)}</tbody></table></div> : <Empty>No practice recorded yet. Start a question to save your first attempt.</Empty>; }
export function useAction<TVariables, TResult>(fn:(variables:TVariables)=>Promise<TResult>) {
  const cache = useQueryClient();
  return useMutation({ mutationFn:fn, onSuccess:async()=>{ await cache.invalidateQueries(); } });
}
export function CopyButton({text,children}:{text:string;children:ReactNode}) { const [state,setState]=useState(''); return <><button onClick={async()=>{try{await navigator.clipboard.writeText(text);setState('Copied');}catch{setState('Clipboard unavailable. Select and copy the text manually.');}}}>{children}</button>{state && <span role="status" className="small">{state}</span>}{state.startsWith('Clipboard') && <textarea readOnly value={text} aria-label="Text to copy"/>}</>; }
